In [ ]:


# Numpy - Numeric python
# Most powerful package - library

# Numpy - Dimensions

# A - One Dimensional Array
# [A,B] || [A
#           B] - Two Dimensional Array - Row ||column

# Three Dimensional

# Array - storing, manipulating, Similar Data type

# Faster than any mathematical function
# convinient compared to other packages
# Memory effiy
# support multidimensional arrays

# speed(Numpy operation) > speed(lists operation)
# size(Numpy operation) < size(lists operation)
# Memory optimization(Numpy) > memory optimization (list operations)

In [ ]:
# Install Numpy - pip3 install Numpy // pip install Numpy

In [ ]:
import numpy as np

In [ ]:

  arr1D = np.array([1,2,3,4,5])
  print(arr1D)

[1 2 3 4 5]


In [ ]:
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
allZeros = np.zeros((2,3,))
print(allZeros)

allOnes = np.ones((2,3))
print(allOnes)

allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creating random matrices

#between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.71910809 0.17347681 0.11713073]
 [0.05095174 0.7916846  0.84709808]
 [0.43936836 0.99647798 0.66904956]]
[[10 17 16]
 [16 10 19]
 [11 16 17]]


In [ ]:
# Array properties

arr = np.array([[1,2,3,4,],[0,3,4,5,]])
print(arr)

# shape of array
print(f' the shape of the array is {arr.shape}')

# size of array
print(f' the size of the array is {arr.size}')

#Datatype of array
print(f' the Data type of the array is {arr.dtype}')

# Dimensions of array
print(f' the dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [0 3 4 5]]
 the shape of the array is (2, 4)
 the size of the array is 8
 the Data type of the array is int64
 the dimension of the array is 2


In [ ]:
# Indexing and sliding
# Access the elements in 1D array

arr = np.array([1,2,3,4])
print(arr)
print(arr[3])


# sliding the elements
print(arr[0:3])

#Access the elements in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # Frist row with all columns
print(arr2[:,0]) #Frist columns with all column

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
# l1 = []
# [l1.append(_) for _ in range(10)]

l1 = np.arange(10,-10,-3)
print(l1)

[10  7  4  1 -2 -5 -8]


In [ ]:
# Mathematics operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f' the sum of a and b is {a + b}')
print(f' the difference of a and b is {a - b}')
print(f' the product of a and b is {a * b}')
print(f' the division of a and b is {a / b}')

 the sum of a and b is [4 6 8]
 the difference of a and b is [-2 -2 -2]
 the product of a and b is [ 3  8 15]
 the division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
# Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,5],[8,8],[1,1]])

# Dot product --- product = AB -- A m x n -- B n x p
c = np.dot(b1,b2)
print(c)

[[24 24]
 [38 38]]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 5]
 [8 8]
 [1 1]]
